### ISSUE TITLE
Get rid of tmp folder

### ISSUE THREAD

**Issue by jlengrand** [gcatanese/openapi-generator-postman-v2#13]
We currently use a tmp folder with a fatjar from the openapi-cli dependendy.

We should build the docker image in a clean way, by either generating a fat jar or at least getting using the copy-dependency plugin.

**Comment by gcatanese** [comment]
Maybe an option is to fetch the latest artifact from https://oss.sonatype.org/content/repositories/snapshots/org/openapitools/openapi-generator-cli/6.3.0-SNAPSHOT/
